site_name: Geomorphology
site_url: https://pulakeshpradhan.github.io/geomorphology/
repo_url: https://github.com/pulakeshpradhan/geomorphology
repo_name: pulakeshpradhan/geomorphology
edit_uri: edit/main/docs/
theme:
  name: material

  palette: 
    - scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulakeshpradhan
    - icon: fontawesome/solid/globe
      link: https://pulakeshpradhan.github.io/

nav:
  - Home: index.md
  - Unit I - Geomorphic Processes:
    - Geomorphic Processes and Landforms: unit-1/index.md
    - Natural vs. Anthropogenic Influences: unit-1/concept-hazards-disasters.md
    - Classification of Landforms: unit-1/natural-manmade-hazards.md
    - Landform Categorization: unit-1/types-of-hazards.md
    - Environmental Vulnerability: unit-1/vulnerability-risk.md
    - Landscape Management: unit-1/prevention-mitigation.md
    - üìù Self Assessment (Questions): unit-1/questions.md
  - Unit II - Landscape Evolution:
    - Dynamic Earth Introduction: unit-2/index.md
    - Geologic Time and Planning: unit-2/pre-disaster-planning.md
    - Active Surface Processes: unit-2/during-disaster-management.md
    - Post-Evolution Resilience: unit-2/post-disaster-planning.md
    - Community Landscape Adaptation: unit-2/community-preparedness.md
    - Role of Stakeholders: unit-2/stakeholders.md
    - üìù Self Assessment (Questions): unit-2/questions.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css

extra_javascript:
  - javascripts/mobile-nav.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Geomorphology Study Portal | Prepared by <a href="https://pulakeshpradhan.github.io/">Pulakesh Pradhan</a>
